name: digital_quiz_competition_platform
description: A digital quiz competition platform.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.2
  provider: ^6.1.1
  intl: ^0.19.0
  http: ^1.1.0
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  flutter_animate: ^4.5.0
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  lottie: ^3.3.1
  curved_navigation_bar: ^1.0.3
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  video_player: ^2.8.2
  visibility_detector: ^0.4.0+2
  flutter_staggered_grid_view: ^0.7.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/images/
   
