// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc6DaNZUbsVN0uwptaMqjQS_HwiWTs6RM',
    appId: '1:925025954218:web:5131e9bd8e1e7a9b6ee3d3',
    messagingSenderId: '925025954218',
    projectId: 'digital-quiz-71822',
    authDomain: 'digital-quiz-71822.firebaseapp.com',
    storageBucket: 'digital-quiz-71822.firebasestorage.app',
    measurementId: 'G-49HC2PQ0CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeEHHEcVIm-TKo3bWE2Eua_Xa512XsIOQ',
    appId: '1:925025954218:android:ddb8b693e62cb30f6ee3d3',
    messagingSenderId: '925025954218',
    projectId: 'digital-quiz-71822',
    storageBucket: 'digital-quiz-71822.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDalktyj7dafH6PJrMgKbXOwzJM7Q1BlzM',
    appId: '1:925025954218:ios:e70f5c1cc3e70ca96ee3d3',
    messagingSenderId: '925025954218',
    projectId: 'digital-quiz-71822',
    storageBucket: 'digital-quiz-71822.firebasestorage.app',
    iosBundleId: 'com.example.digitalQuizCompetitionPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDalktyj7dafH6PJrMgKbXOwzJM7Q1BlzM',
    appId: '1:925025954218:ios:e70f5c1cc3e70ca96ee3d3',
    messagingSenderId: '925025954218',
    projectId: 'digital-quiz-71822',
    storageBucket: 'digital-quiz-71822.firebasestorage.app',
    iosBundleId: 'com.example.digitalQuizCompetitionPlatform',
  );
}
